/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16. 7. 1 오전 5:15' with Gradle 2.13
 *
 * @author Administrator, @date 16. 7. 1 오전 5:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
